import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>

         
        {/* <footer className="bg-gray-800 text-white py-4">
          <div className="container mx-auto text-center">
            <p>© 2025 Nama Perusahaan. All rights reserved.</p>
          </div>
        </footer> */}
      </body>
    </html>
  );
}